# Generated by Django 5.1.1 on 2024-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpulisting',
            name='seller_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
