# Generated by Django 5.1.1 on 2024-10-05 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gpulisting_current_highest_bid_gpulisting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpulisting',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 18, 52, 58, 21620, tzinfo=datetime.timezone.utc)),
        ),
    ]
