# Generated by Django 5.1.1 on 2024-10-05 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_gpulisting_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpulisting',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 20, 9, 7, 851965, tzinfo=datetime.timezone.utc)),
        ),
    ]
