# Generated by Django 5.1.1 on 2024-10-06 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_gpulisting_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpulisting',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 7, 16, 14, 233067, tzinfo=datetime.timezone.utc)),
        ),
    ]
