# Generated by Django 5.1.1 on 2024-10-06 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_gpulisting_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpulisting',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 16, 10, 32, 479164, tzinfo=datetime.timezone.utc)),
        ),
    ]
