# Generated by Django 5.1.1 on 2024-10-07 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_gpulisting_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpulisting',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 11, 58, 39, 739835, tzinfo=datetime.timezone.utc)),
        ),
    ]
